# Generated by Django 3.1.2 on 2021-04-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='regularreplacementpos',
            name='bound_regrepl',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='RegRepl.regularreplacement', verbose_name='Штатное замещение '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='dep',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='RegRepl.departament', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='dir',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='RegRepl.dirdepartament', verbose_name='Дирекция '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='subdep',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='RegRepl.subdepartament', verbose_name='Субподразделение '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='units',
            field=models.FloatField(db_index=True, max_length=256, verbose_name='Кол-во едениц по штатному расписанию '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='units_rr',
            field=models.FloatField(db_index=True, max_length=256, verbose_name='Кол-во едениц по штатному замещению '),
        ),


        migrations.AddField(
            model_name='subdepartament',
            name='location',
            field=models.ForeignKey(default='1', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='RegRepl.location', verbose_name='Территория '),
        ),
    ]
