# Generated by Django 3.1.2 on 2021-04-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='united_with',
        ),
    ]
