# Generated by Django 3.1.2 on 2021-04-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreplacementpos',
            name='employer1',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='Сотрудник1 '),
        ),
        migrations.AddField(
            model_name='regularreplacementpos',
            name='employer2',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='Сотрудник1 '),
        ),
        migrations.AddField(
            model_name='regularreplacementpos',
            name='employer3',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='Сотрудник1 '),
        ),
    ]
