# Generated by Django 3.1.7 on 2022-03-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0002_auto_20220328_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'ordering': ['iter'], 'verbose_name': 'Подразделение'},
        ),
        migrations.AddField(
            model_name='departament',
            name='iter',
            field=models.IntegerField(default=1, verbose_name='Порядок '),
        ),
    ]
