# Generated by Django 3.1.2 on 2021-04-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0002_auto_20210401_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='dirdep',
        ),
        migrations.RemoveField(
            model_name='subdepartament',
            name='dep',
        ),
        migrations.AddField(
            model_name='departament',
            name='subdep',
            field=models.ManyToManyField(to='RegRepl.SubDepartament', verbose_name='Cубподразделения '),
        ),
        migrations.AddField(
            model_name='dirdepartament',
            name='dep',
            field=models.ManyToManyField(to='RegRepl.Departament', verbose_name='Подразделения '),
        ),
        migrations.AddField(
            model_name='regularreplacementpos',
            name='comm',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='Комментарий '),
        ),
    ]
