# Generated by Django 3.1.2 on 2021-04-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0003_auto_20210401_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreplacementpos',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Ставка свободна '),
        ),
    ]
