# Generated by Django 3.1.2 on 2021-04-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0003_auto_20210407_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='bound_regrepl',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='RegRepl.regularreplacement', verbose_name='Штатное замещение '),
        ),
    ]
