# Generated by Django 3.1.2 on 2021-04-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0003_departament_united_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='united_with',
            field=models.ForeignKey(default='1', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='RegRepl.departament', verbose_name='Объеденить с  '),
        ),
    ]
