# Generated by Django 3.1.7 on 2022-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0004_auto_20220328_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dirdepartament',
            options={'ordering': ['iter'], 'verbose_name': 'Дирекция'},
        ),
        migrations.AddField(
            model_name='dirdepartament',
            name='iter',
            field=models.IntegerField(default=1, verbose_name='Порядок '),
        ),
    ]
