# Generated by Django 3.1.2 on 2021-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0004_regularreplacementpos_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='employer1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='Сотрудник1 '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='employer2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='Сотрудник1 '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='employer3',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='Сотрудник1 '),
        ),
    ]
