# Generated by Django 3.1.2 on 2021-04-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0004_auto_20210407_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='subdep',
            field=models.ForeignKey(blank=True, default='None', on_delete=django.db.models.deletion.CASCADE, to='RegRepl.subdepartament', verbose_name='Субподразделение '),
        ),
    ]
