# Generated by Django 3.1.2 on 2021-04-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0005_auto_20210414_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='united_with',
        ),
    ]
