# Generated by Django 3.1.2 on 2021-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0005_auto_20210402_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='comm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='Комментарий '),
        ),
    ]
