# Generated by Django 3.1.2 on 2021-04-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0007_auto_20210407_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreplacement',
            name='location',
            field=models.CharField(choices=[('Головное предприятие', 'Головное предприятие'), ('Филиал "Центральный"', 'Филиал "Центральный')], default='Головное предприятие', max_length=256, verbose_name='Территория '),
        ),
    ]
