# Generated by Django 3.1.2 on 2021-04-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0007_departament_united_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularreplacementpos',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='regularreplacementpos',
            name='cat_rr',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
