# Generated by Django 3.1.2 on 2021-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0008_regularreplacement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='units',
            field=models.FloatField(db_index=True, max_length=256, verbose_name='Кол-во едениц по штатному расписанию '),
        ),
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='units_rr',
            field=models.FloatField(db_index=True, max_length=256, verbose_name='Кол-во едениц по штатному замещению '),
        ),
    ]
