# Generated by Django 3.1.2 on 2021-04-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0009_auto_20210415_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='iter',
        ),
    ]
