# Generated by Django 3.1.2 on 2021-04-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0010_remove_departament_iter'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='iter',
            field=models.IntegerField(default=1, verbose_name='Порядок '),
        ),
    ]
