# Generated by Django 3.1.7 on 2021-06-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0011_departament_iter'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreplacementpos',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Ставка выведена '),
        ),
    ]
