# Generated by Django 3.1.2 on 2021-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0012_regularreplacementpos_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreplacementpos',
            name='payment_rr',
            field=models.CharField(blank=True, max_length=3, verbose_name='Ступень оплаты по штатному замещению'),
        ),
    ]
