# Generated by Django 3.1.7 on 2022-03-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0013_auto_20210621_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='united_with',
        ),
        migrations.AddField(
            model_name='regularreplacementpos',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name='Руководитель подразделения(отдела)'),
        ),
    ]
