# Generated by Django 3.1.7 on 2022-03-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegRepl', '0015_departament_united_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='united_with',
        ),
    ]
